@prod_domain = https://gym-membership-project.onrender.com
  @dev_domain = http://localhost:3000
  @memberId = 67d556af1b2495a457a44ac8
  
### Get all members
GET {{dev_domain}}/members
###
GET {{prod_domain}}/members

### Get specific contact by id
GET {{dev_domain}}/members/{{memberId}}
###
GET {{prod_domain}}/members/{{memberId}}
### Create new contact
POST {{dev_domain}}/members
content-type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "weight": "any",
  "phone": "any",
  "address": "any",
  "favoriteWorkout": "any",
  "birthday": "any"
}
###
POST {{prod_domain}}/members
content-type: application/json

{
  "firstName": "Kevo",
  "lastName": "Superstar",
  "weight": "67",
  "phone": "0737-000-400",
  "address": "Karen",
  "favoriteWorkout": "Biceps",
  "birthday": "17-12-199"
}
### Update member
PUT {{dev_domain}}/members/{{memberId}}
content-type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "weight": "any",
  "phone": "any",
  "address": "any",
  "favoriteWorkout": "any",
  "birthday": "any"
}
###
PUT {{prod_domain}}/members/{{memberId}}
content-type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "weight": "any",
  "phone": "any",
  "address": "any",
  "favoriteWorkout": "any",
  "birthday": "any"
}
### Delete contact
DELETE {{dev_domain}}/members/{{memberId}}
###
DELETE {{prod_domain}}/members/{{memberId}}